aqi_dbt:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{ env_var('MYSQL_HOST') }}"
      port: "{{ env_var('MYSQL_PORT') | int }}"
      schema: "{{ env_var('MYSQL_DB') }}"
      username: "{{ env_var('MYSQL_USER') }}"
      password: "{{ env_var('MYSQL_PASSWORD') }}"
      threads: 4
